apiVersion: v2
name: oxy-app
description: A Helm chart for Oxy application deployment on kubernetes
type: application
version: 0.4.1
appVersion: "0.5.19"
keywords:
  - oxy
maintainers:
  - name: Oxy Team
    email: hello@oxy.tech
  - name: Luong Vo
    email: luong@oxy.tech

dependencies:
  - name: postgres
    version: "1.6.1"
    repository: "https://groundhog2k.github.io/helm-charts/"
    condition: database.postgres.enabled
  - name: clickhouse
    version: "9.4.4"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: database.clickhouse.enabled
    alias: clickhouseSubchart
