apiVersion: v2
name: oxy-app
description: A Helm chart for Oxy application deployment on kubernetes
type: application
version: 0.3.1
appVersion: "0.3.19"
keywords:
  - oxy
maintainers:
  - name: Oxy Team
    email: hello@oxy.tech
  - name: Luong Vo
    email: luong@oxy.tech

dependencies:
  - name: cluster
    version: 0.5.0
    repository: "https://cloudnative-pg.github.io/charts"
    condition: database.postgres.enabled
    alias: postgresql
