apiVersion: v2
name: oxy
description: Oxy with Docker-in-Docker â€” self-contained deployment using `oxy start` to manage all services internally
type: application
version: 0.1.0
appVersion: "0.5.11"
maintainers:
  - name: Oxy Team
    url: https://oxy.tech
  - name: Luong Vo
    url: https://github.com/luongvo
keywords:
  - oxy
  - docker-in-docker
  - dind
home: https://oxy.tech
sources:
  - https://github.com/oxy-hq/charts
