apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "oxy-app.fullname" .) .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oxy-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "oxy-app.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: traffic-port
  {{- if .Values.app.internalHost }}
  - port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.app.internalPort }}
    protocol: TCP
    name: internal-port
  {{- end }}
  type: {{ .Values.service.type }}
