{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oxy-start.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oxy-start.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
