{{- if and .Values.externalSecrets.create (not (empty .Values.externalSecrets.storeRef.name)) }}
{{- $storeName := $.Values.externalSecrets.storeRef.name }}
{{- $storeKind := $.Values.externalSecrets.storeRef.kind }}

{{- range $i, $s := $.Values.externalSecrets.envSecretNames }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $s }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: {{ $s }}
    creationPolicy: Owner
  {{- $mapping := index $.Values.externalSecrets.envSecretMappings $s }}
  {{- if $mapping }}
  data:
  {{- range $k, $v := $mapping }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $v | quote }}
  {{- end }}
  {{- else }}
  data: []
  {{- end }}
{{- end }}

{{- range $i, $fs := $.Values.externalSecrets.fileSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fs.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $storeName }}
    kind: {{ $storeKind }}
  target:
    name: {{ $fs.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ default $fs.key $fs.key }}
      remoteRef:
        key: {{ $fs.path | default $fs.name }}
{{- end }}
{{- end }}
