{{- if and .Values.gitSync.enabled .Values.httpAuth.username .Values.httpAuth.password (not .Values.httpAuth.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oxy-start.fullname" . }}-http-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oxy-start.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.httpAuth.password | quote }}
{{- end }}
