{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "oxy-start.fullname" . }}-pdb
  labels:
    {{- include "oxy-start.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- if .Values.pdb.selector }}
      {{- range $k, $v := .Values.pdb.selector }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
      {{- else }}
      {{- include "oxy-start.selectorLabels" . | nindent 6 }}
      {{- end }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
{{- end }}
