apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "oxy-start.fullname" .) .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oxy-start.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "oxy-start.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: traffic-port
  type: {{ .Values.service.type }}
